project:
  type: website
website:
  title: Rushi's Furnace
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shahrushi2003
      - icon: twitter-x
        href: https://twitter.com/RushiShah1729
format:
  html:
    theme:
      dark: cyborg
      light: flatly
    smooth-scroll: true
    css: styles.css
    mainfont: "Gill Sans"
    image-height: 150px