project:
  type: website
website:
  title: Rushi's Furnace
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css